language: python
python:
   - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# Run tests
script:
   - nosetests --exe -v --with-coverage --cover-package=app

after_success:
  - coveralls

services:
  - postgresql
  
before_script:
  - psql -c 'create database storemanager;' -U postgres
  - psql -c 'create database storemanager_testdb;' -U postgres

  - psql -c "ALTER USER postgres WITH PASSWORD 'nic';" -U postgres

env:
  - DATABASE_URL= "dbname='storemanager' host='localhost' port='5432' user='postgres' password='nic'"
