language: python

python:    

 - "3.6"

 

services:

  - postgres

install:    

 - pip install -r requirements.txt

 - pip install codeclimate-test-reporter

 

before_script:

  - psql -c "create database store;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'nic';" -U postgres
script:    

 

- nosetests --with-coverage

 - coveralls

 

after_success:

 - coveralls

 - codeclimate-test-reporter

cache: pip 
